[2024-11-17T19:29:52.722+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-17T19:29:52.731+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_conn_dag.upload_to_s3 manual__2024-11-17T19:29:52.323616+00:00 [queued]>
[2024-11-17T19:29:52.734+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_conn_dag.upload_to_s3 manual__2024-11-17T19:29:52.323616+00:00 [queued]>
[2024-11-17T19:29:52.734+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-17T19:29:52.740+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-11-17 19:29:52.323616+00:00
[2024-11-17T19:29:52.742+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=251) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-17T19:29:52.743+0000] {standard_task_runner.py:72} INFO - Started process 252 to run task
[2024-11-17T19:29:52.744+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 's3_conn_dag', 'upload_to_s3', 'manual__2024-11-17T19:29:52.323616+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/sample_aws_connection.py', '--cfg-path', '/tmp/tmp33aqz6c8']
[2024-11-17T19:29:52.744+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask upload_to_s3
[2024-11-17T19:29:52.768+0000] {task_command.py:467} INFO - Running <TaskInstance: s3_conn_dag.upload_to_s3 manual__2024-11-17T19:29:52.323616+00:00 [running]> on host 215aff354163
[2024-11-17T19:29:52.802+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_conn_dag' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T19:29:52.323616+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-17T19:29:52.323616+00:00'
[2024-11-17T19:29:52.803+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-17T19:29:52.813+0000] {base.py:84} INFO - Retrieving connection 's3_conn'
[2024-11-17T19:29:52.814+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-11-17T19:29:53.900+0000] {hook.py:208} WARNING - Data lineage tracking is disabled. Register a hook lineage reader to start tracking hook lineage.
[2024-11-17T19:29:53.904+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-17T19:29:53.920+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-17T19:29:53.921+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=s3_conn_dag, task_id=upload_to_s3, run_id=manual__2024-11-17T19:29:52.323616+00:00, execution_date=20241117T192952, start_date=20241117T192952, end_date=20241117T192953
[2024-11-17T19:29:53.975+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-17T19:29:53.990+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-17T19:29:53.991+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
