[2024-11-14T03:09:35.030+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-14T03:09:35.038+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: en_species_etl.extract_data manual__2024-11-14T03:09:33.783357+00:00 [queued]>
[2024-11-14T03:09:35.040+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: en_species_etl.extract_data manual__2024-11-14T03:09:33.783357+00:00 [queued]>
[2024-11-14T03:09:35.041+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-14T03:09:35.045+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2024-11-14 03:09:33.783357+00:00
[2024-11-14T03:09:35.049+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=141) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-14T03:09:35.049+0000] {standard_task_runner.py:72} INFO - Started process 142 to run task
[2024-11-14T03:09:35.050+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'en_species_etl', 'extract_data', 'manual__2024-11-14T03:09:33.783357+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/en_species_dag.py', '--cfg-path', '/tmp/tmp9pt315j6']
[2024-11-14T03:09:35.050+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask extract_data
[2024-11-14T03:09:35.072+0000] {task_command.py:467} INFO - Running <TaskInstance: en_species_etl.extract_data manual__2024-11-14T03:09:33.783357+00:00 [running]> on host 0f3a788f39c1
[2024-11-14T03:09:35.105+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='en_species_etl' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T03:09:33.783357+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T03:09:33.783357+00:00'
[2024-11-14T03:09:35.106+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-14T03:10:43.606+0000] {logging_mixin.py:190} INFO - Page 1 data downloaded!
[2024-11-14T03:11:59.540+0000] {logging_mixin.py:190} INFO - Page 2 data downloaded!
[2024-11-14T03:13:13.780+0000] {logging_mixin.py:190} INFO - Page 3 data downloaded!
[2024-11-14T03:14:25.357+0000] {logging_mixin.py:190} INFO - Page 4 data downloaded!
[2024-11-14T03:16:05.186+0000] {logging_mixin.py:190} INFO - Page 5 data downloaded!
[2024-11-14T03:17:44.702+0000] {logging_mixin.py:190} INFO - Page 6 data downloaded!
[2024-11-14T03:18:48.695+0000] {logging_mixin.py:190} INFO - Page 7 data downloaded!
[2024-11-14T03:19:57.391+0000] {logging_mixin.py:190} INFO - Page 8 data downloaded!
[2024-11-14T03:21:04.605+0000] {logging_mixin.py:190} INFO - Page 9 data downloaded!
[2024-11-14T03:22:14.665+0000] {logging_mixin.py:190} INFO - Page 10 data downloaded!
[2024-11-14T03:23:22.137+0000] {logging_mixin.py:190} INFO - Page 11 data downloaded!
[2024-11-14T03:24:26.499+0000] {logging_mixin.py:190} INFO - Page 12 data downloaded!
[2024-11-14T03:25:28.134+0000] {logging_mixin.py:190} INFO - Page 13 data downloaded!
[2024-11-14T03:26:33.320+0000] {logging_mixin.py:190} INFO - Page 14 data downloaded!
[2024-11-14T03:27:36.159+0000] {logging_mixin.py:190} INFO - Page 15 data downloaded!
[2024-11-14T03:28:37.955+0000] {logging_mixin.py:190} INFO - Page 16 data downloaded!
[2024-11-14T03:29:43.928+0000] {logging_mixin.py:190} INFO - Page 17 data downloaded!
[2024-11-14T03:29:54.244+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/extract_en_species.py", line 95, in main
    row = transform_assess(id, data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/extract_en_species.py", line 70, in transform_assess
    data['population_trend']['code'],
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-11-14T03:29:54.255+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=en_species_etl, task_id=extract_data, run_id=manual__2024-11-14T03:09:33.783357+00:00, execution_date=20241114T030933, start_date=20241114T030935, end_date=20241114T032954
[2024-11-14T03:29:54.267+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-14T03:29:54.267+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task extract_data ('NoneType' object is not subscriptable; 142)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/extract_en_species.py", line 95, in main
    row = transform_assess(id, data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/extract_en_species.py", line 70, in transform_assess
    data['population_trend']['code'],
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-11-14T03:29:54.286+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-14T03:29:54.304+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T03:29:54.307+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
